#!/bin/bash

# FlickX Quick Start Script for VSCode Terminal
# This script helps you quickly run the project

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           FlickX Movie Recommendation System                 ║"
echo "║                  Quick Start Guide                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📖 For detailed instructions, see VSCODE_GUIDE.md"
echo ""
echo "🚀 Quick Commands:"
echo ""
echo "  1. Install all dependencies:"
echo "     npm run setup"
echo ""
echo "  2. Run full stack (Backend + Frontend):"
echo "     npm run dev"
echo ""
echo "  3. Run backend only:"
echo "     cd backend && npm start"
echo ""
echo "  4. Run frontend only:"
echo "     cd frontend && npm start"
echo ""
echo "💡 VSCode Users:"
echo "   - Press Ctrl+Shift+B (Cmd+Shift+B on Mac) to run full stack"
echo "   - Or press Ctrl+Shift+P and type 'Tasks: Run Task'"
echo ""
echo "🐛 Debug:"
echo "   - Press F5 or use the Debug panel (Ctrl+Shift+D)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
